version: '3.0'

services:
  streamlit:
    build:
      context: .
      dockerfile: deployment/app/Dockerfile
    hostname: streamlit
    container_name: streamlit
    command: streamlit run omic_learn.py --browser.gatherUsageStats False
    restart: on-failure
    ports:
      - 8501:8501
    networks:
      nginx_network:
        aliases:
          - streamlit
  nginx:
    build:
      context: deployment/nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - streamlit:streamlit
    depends_on:
      - streamlit
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge